### PR TITLE
Pause at Node Behavior

### PR DESCRIPTION
**Pull request by nikku**
This gives users the ability to pause process simulation at a given node. Essentially this resembles what software developers call a _breakpoint_. The pause at node state can be toggled via click and remains visual on the diagram, if enabled.

capture Hzz5N1_optimized

Along with the global pause and resume behavior (triggered via the global pause/play button as well as via the `SPACEBAR`) this shall give users all they need to simulate certain process behavior step by step:

capture xy7q5S_optimized

----

This is an alternative to https://github.com/bpmn-io/bpmn-js-token-simulation/pull/85. Read https://github.com/bpmn-io/bpmn-js-token-simulation/pull/85#issuecomment-991720830 for my rationale why I belive this is the better way to approach things.

----

Closes https://github.com/bpmn-io/bpmn-js-token-simulation/issues/9

### CODE REVIEW

**Comment by jonathanlukas** [comment]
Hi :) I see that the behaviour is a breakpoint. That is probably the reason why there is a dot as symbol for pausing.
I love the feature and I cannot wait to use it on my own!

My suggestion would be to use the (maybe more business-user-scoped) Pause-Element (like the Pause-Button on a Youtube video). 
In my opinion, this is more intuitive for a user. Also, regarding the potential use-case in completely business-scoped BPMN modelling tools, not every user will understand the idea of a breakpoint.

**Comment by nikku** [comment]
@jonathanlukas Very good feedback. In fact, I was not sure about the appropriate iconography myself. I'll give pause a try. Given that pause is already part of the function (global pause button), that could make things easier. We also call it _pause point_ rather than _break point_ already.

**Comment by nikku** [comment]
@jonathanlukas A sketch of your proposed improvement (pause instead of _breakpoint_): 

Feels much better, as expected :smile_cat:.

**Comment by jonathanlukas** [comment]
@nikku I love it :) Thank you!

**Comment by nikku** [comment]
Released with [v0.23.0; try it out](https://bpmn-io.github.io/bpmn-js-token-simulation/modeler.html?e=1).

**Pull request merged**
