### PR TITLE
Allow Errors To Propagate Upwards

### LINKED ISSUE #187: Make Error Events Bubble Up
### Is your feature request related to a problem? Please describe.

Error End Events trigger nearby event subprocesses or boundary events but they do not bubble up the scope hierarchy.

<details>
<summary>Demo</summary>

visual-demo
</details>

### Describe the solution you'd like

Make error events bubble up the same way escalation events do.

<details>
<summary>Demo</summary>

visual-demo-esc
</details>

This is backed by the spec, since the hierarchy is explicitly mentioned in the description.

error-end-event

### Describe alternatives you've considered

Not implementing this feature means keeping a mismatch of error and escalation handling. The spec describes both event types almost identically, so a mismatch doesn't seem warranted.

### Additional context

In Camunda 8 both error and escalation events bubble up.
Practically, I don't know about Camunda 7, but the documentation for [_escalation_ events](https://docs.camunda.org/manual/7.17/reference/bpmn20/events/escalation-events/#escalation-intermediate-throw-event) gives a positive hint:
> Like an **error event**, an escalation event is propagated to upper scopes (e.g., from sub-process or call activity) till it is caught.

### PR DESCRIPTION
**Pull request by sombrek**
### Proposed Changes

Closes #187

Errors now bubble up the hierarchy, just like escalations do.

The `EventBehavior` of errors was enhanced to resemble that of escalation events. New tests were added.

<details>
<summary>Demo</summary>

visual-demo
</details>

### CODE REVIEW

**Comment by barmac** [comment]
Thanks for your contribution. We'll have a look at this soon.

One minor thing which I noticed: Please add `Closes #187` to the commit body.

**Comment by barmac** [comment]
Besides that, it works correctly. Thank you!

**Comment by sombrek** [comment]
> I added the "Closes" clause.

Excellent. Thank you. I'll try to remember it next time.

**Comment by barmac** [comment]
Released as v0.35.1 🚀

**Comment by nikku** [comment]
:clap: Simple and easy implementation, relying on core provided infrastructure :rocket:

**Pull request merged**
