### PR TITLE
Make Parallel Join Spec Compliant

### LINKED ISSUE #130: Parallel Join not behaving correctly
### Describe the Bug

The parallel join does not behave correctly. It waits for the number of tokens equal to the number of incoming sequence flows. However, it does not ensure these are actually coming from all incoming sequence flows. (See gif)

### Steps to Reproduce

See GIF
parallelJoin

### Expected Behavior

> The concurrent paths can be joined using a parallel gateway with multiple incoming sequence flows. The process instance waits at the parallel gateway until each incoming sequence is taken.

https://docs.camunda.io/docs/components/modeler/bpmn/parallel-gateways/

I am not sure what the standard says, but I would hope it's the same ;) 

### Environment

Library Version: bpmn-js-token-simulation@0.33.0

### PR DESCRIPTION
**Pull request by sombrek**
### Proposed Changes

Closes #130

Parallel gateways now remember which sequence flows already provided a token.
The join activates every time at least one token was provided on all incoming flows. One token per flow is consumed on join.

@barmac
Exiting a sequence flow now provides a source where a token came from. That idea was taken from #143, but this PR does not cover inclusive joins. If the solution is accepted, it could be a starting point for inclusive gateways.

<details>
<summary>Visual demo</summary>

visual-demo
</details>

### CODE REVIEW

**Comment by nikku** [comment]
@sombrek This looks great! I'll check if there is a better way to store incoming tokens than [global state](https://github.com/bpmn-io/bpmn-js-token-simulation/pull/182/commits/416da25c9aa93d788b74d22ea771f626a8ed4007#diff-f5dc2a5ff182bbb4ddd3482883fbcd7164e56f3e647d70174f7a6d315ac7053fR16) tomorrow. Potentially these could be stored in the parent scope.

**Comment by nikku** [comment]
Thanks again for your contribution @sombrek! I was stumbling over the global state you introduced and thought there would be a simpler way, given that we already collect execution via scopes, and hence track "active executions for a given element".

The only missing bit was to apply your filtering logic to the existing scopes scopes on this node, and properly tag initiators when entering a scope (from a sequence flow exit).

Cf. https://github.com/bpmn-io/bpmn-js-token-simulation/pull/182/commits/ecfaba1098d801f760fce4bd26c0887778cc29fb greatly simplifying your implementation and https://github.com/bpmn-io/bpmn-js-token-simulation/pull/182/commits/59c85115c333676dd17ea7a9840f622ded6feecb refactoring the behavior just a bit.

**Review by nikku — APPROVED** [review]

**Comment by nikku** [comment]
CC @barmac because the "source" is gone (again). We track such information via scopes and their hierarchy.

**Comment by nikku** [comment]
Released via https://github.com/bpmn-io/bpmn-js-token-simulation/releases/tag/v0.34.5.

**Comment by sombrek** [comment]
> I was stumbling over the global state you introduced and thought there would be a simpler way, given that we already collect execution via scopes, and hence track "active executions for a given element".

@nikku Thank you for all the additional work you've put in. I reckon I could have done it without the global state, but I failed to properly translate scopes to my understanding of tokens. I'll study your changes to get a better understanding.

**Pull request merged**
