### PR TITLE
Add basic bpmn-js@9 / collapsed sub-processes compatibility

### PR DESCRIPTION
**Pull request by marstamm**
related to https://github.com/bpmn-io/internal-docs/issues/340

recording (54)

### CODE REVIEW

**Comment by nikku** [comment]
I did update the PR to build on top of recent token simulation changes. The current state is that it does not break with `bpmn-js@9`, it does not work 100% properly either:

capture mVi5CJ_optimized

What works: 

* Execution through embedded, collapsed sub-process
* Pausing inside embedded, collapsed sub-process
* Scope cancelation via boundary event
* Backwards compatible with bpmn-js@8

What does not work yet / shall be improved:

* Pause icon shows on sub-process plane => Do not show it
* No indication that tokens are active inside sub-process => Show them bouncing (cf. token on paused node) on sub-process activity
* Triggering events / event registration inside sub-process planes broken

What is missing: 

* Test coverage

**Comment by nikku** [comment]
I think it makes sense to roll out basic compatibility / test coverage quickly and follow up with everything else at a later stage. WDYT @marstamm?

**Comment by marstamm** [comment]
I agree with the assessment. We should have something that at least works with single plane processes for the release

**Comment by marstamm** [comment]
We can look into the improvements in follow-up issues. I already have Ideas for token visibility, we had a similar challenge in the Cockpit integration

**Comment by marstamm** [comment]
I added a [basic test case](https://github.com/bpmn-io/bpmn-js-token-simulation/pull/87/commits/205d0291a895f41339ab485f18c61cf2360cf65b) for the collapsed subprocess path. Is there anything else we should consider before merging this PR @nikku ?

**Comment by nikku** [comment]
That should do it for now.

**Comment by nikku** [comment]
Move to review if you are done from your end and I'll do a final check.

**Comment by nikku** [comment]
Extracted follow up issue: https://github.com/bpmn-io/bpmn-js-token-simulation/issues/114.

**Review by nikku — APPROVED** [review]

**Pull request merged**
