### PR TITLE
Manual trigger user tasks

### LINKED ISSUE #9: Manually trigger user tasks
__Problem Description__

The token should wait at user tasks (just like at events) and can be triggered manually to continue.

__Describe the Solution__

* Optionally, any activity may be marked as _pausing_, making incoming tokens halt at it.

### PR DESCRIPTION
**Pull request by Ichigo85**
- New "Automatic mode" toggle next to animation speed
- Tests added

Closes #9

### CODE REVIEW

**Comment by nikku** [comment]
Could you elaborate what you did and why you did it?

I personally do not see the use-case for step-by-step execution and would rather go for manual pausing at certain points. So rather than doing what you propose, add the ability to add an explicit break point when hovering over an element.

If such "break point" element is reached, the simulator pauses there.

**Comment by Ichigo85** [comment]
I created another toggle button just like ToggleMode and implemented the behaviour on ActivityBehaviour, to waitAtElement if this button is active.
The use-case for step-by-step execution is mainly for training purposes, or if someone wants to explain a model to a client. In this way you can show step-by-step what happens.

**Comment by ingorichtsmeier** [comment]
Hi @nikku, 
this feature makes it much easier to explain processes to absolute beginners. 
The process continues, after the task is completed and you can take your time as a trainer to explain it. 
And simulate the work (and time) that is required to fulfill the task.

**Comment by nikku** [comment]
@ingorichtsmeier Thanks for jumping in.

The issue which I'm not 100% confident of is having step by step execution proposed in this PR vs. [being able to _manually pause on certain activities only](https://github.com/bpmn-io/bpmn-js-token-simulation/issues/9#issuecomment-839744981) (i.e. to simulate longer processing time)_. Could you elaborate on why you'd prefer the forced step by step execution rather than providing tools for individual pausing?

**Comment by ingorichtsmeier** [comment]
Well, take one of the first processes from our bpmn training:
07-AND-Gateway
If you want to highlight the different completion times for the "Cook pasta" and "Prepare salad" tasks, you could not do this without a stop-and-continue UI.

Right now we have a powerpoint token animation in the training to highlight the purpose of the parallel joining event.

I would like to do this with the token simulation plugin for every process. It would be nice to continue parallel tokens one after the other with different keys on the keyboard, like (1, 2, 3, ..., a, b, c, ..., z). Or click on them to continue ...

**Comment by ingorichtsmeier** [comment]
As a trainer I want to adjust the token flow to my words. This is difficult with a tool based support and fixed or random wait times.

**Comment by nikku** [comment]
@ingorichtsmeier I think the example you shared is a great starting point to continue the discussion. Is it possible for you to share it (as BPMN) so I can simulate it?

> I would like to do this with the token simulation plugin for every process. It would be nice to continue parallel tokens one after the other with different keys on the keyboard, like (1, 2, 3, ..., a, b, c, ..., z). Or click on them to continue ...

This especially makes a lot of sense, however it is also an additional feature request and call to improve our existing (albeit fairly limited) active flow selection facilities.

**Comment by ingorichtsmeier** [comment]
[07-AND-Gateway.bpmn.txt](https://github.com/bpmn-io/bpmn-js-token-simulation/files/6848442/07-AND-Gateway.bpmn.txt)
Here it is.

**Comment by Ichigo85** [comment]
Hi @ingorichtsmeier, thank you very much for your answer 😊 ! I made a few gif examples using your bpmn file to show how my pull request actually works.
Automatic (default) behaviour
Automatic_simulation
Manual behaviour
Manual_simulation


I also thought about your discussion and It came up a "third" option, a hybrid option for automatic simulation which I would like to show with this image (this is just a mockup made with a previous project of mine). 
image

The overlays on the right side of the tasks can be some kind of breakpoints for the simulation. I can create a 'breakpoint mode' where the user can select which elements he wants to manually pause, just by clicking on it, and then the automatic simulation just stops on them, and then continue on user trigger. 
What do you think?

**Comment by nikku** [comment]
@Ichigo85 Great you followed up on this. 

What I imagined was exactly what you've sketched with the third option:

* I can hover over an element and toggle a pause button (adding a break point, effectively).
* As long as elements are on the node pressing the play button will release these tokens. If there are none, the play button toggles the pause on node feature back off.

image

**Comment by Ichigo85** [comment]
Hi @nikku , I don't know. I was thinking on something...Let's say, easier. Without the needs to "keep count" of the tokens to release and stop.
Like, I double click on an element and it creates a breakpoint (waitAtElement on). every time token goes there, it pauses (with the play context pad). On right click on the element, I remove the breakpoint (waitAtElement off).

Actually, on manual mode already works like this, I think. Maybe I am missing something, or we are talking of the same thing looking at different angles 😂

image

**Comment by Ichigo85** [comment]
Sorry, I wanted to make another gif.
Multiple_simulation

**Comment by nikku** [comment]
I was hoping to follow up on this PR but was not able to do it. It is not forgotten! I'll come back sooner or later (after summer vacation, very likely).

**Comment by Ichigo85** [comment]
Hi @nikku , any news about this PR?

**Comment by nikku** [comment]
I've implemented my take on https://github.com/bpmn-io/bpmn-js-token-simulation/issues/9 / this PR via https://github.com/bpmn-io/bpmn-js-token-simulation/pull/91.

Specifically, I added the ability to globally select nodes I want to pause at (i.e. to simulate a specific wait time). Those breakpoints are clearly visible on the diagram:


capture Hzz5N1_optimized

If we consider step to next behavior (which is an entirely different use-case) I'd rather not enable that globally, but as a variation of play/run (run vs. run to next element). This is something users (especially experts) are used to, cf. this UI from a debugger (see that play and step to next are clear calls to actions): 

image

**Comment by nikku** [comment]
Closing this with https://github.com/bpmn-io/bpmn-js-token-simulation/pull/91 merged.

Thanks for your valuable input to help us end up where we ended up everyone @Ichigo85, @ingorichtsmeier!

**Pull request closed without merging**
