### PR TITLE
fix: Ignore message-flow elements

### PR DESCRIPTION
**Pull request by Guchman**
Message-flow is non executable element, so it should be ignored

### CODE REVIEW

**Review by nikku — CHANGES_REQUESTED** [review]
Thanks for your contribution!

Please [add a test case](https://github.com/bpmn-io/bpmn-js-token-simulation/blob/master/test/spec/SimulationSpec.js) that verifies the improved message flow behavior? We'll not be able to merge the PR without it.

**Comment by Guchman** [comment]
> Thanks for your contribution!
> 
> Please [add a test case](https://github.com/bpmn-io/bpmn-js-token-simulation/blob/master/test/spec/SimulationSpec.js) that verifies the improved message flow behavior? We'll not be able to merge the PR without it.

Ok, should I add a new bpmn scheme for the test or I could just add the element to simple.bpmn?

**Comment by nikku** [comment]
> Ok, should I add a new bpmn scheme for the test or I could just add the element to simple.bpmn?

Makes sense to create a new spec / diagram that tests the message flow behavior, both for incoming and outgoing message flows.

**Comment by nikku** [comment]
Thanks for your contribution :tada:.

Great stuff.

**Pull request merged**
